// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_OBSERVABLE_OBSERVATION_H_
#define FLATBUFFERS_GENERATED_OBSERVABLE_OBSERVATION_H_

#include "flatbuffers/flatbuffers.h"

namespace Observation {

struct Observable;

struct Observable FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_INPUT = 4,
    VT_ANOTHER_INPUT = 6
  };
  const flatbuffers::Vector<float> *input() const {
    return GetPointer<const flatbuffers::Vector<float> *>(VT_INPUT);
  }
  int32_t another_input() const {
    return GetField<int32_t>(VT_ANOTHER_INPUT, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_INPUT) &&
           verifier.VerifyVector(input()) &&
           VerifyField<int32_t>(verifier, VT_ANOTHER_INPUT) &&
           verifier.EndTable();
  }
};

struct ObservableBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_input(flatbuffers::Offset<flatbuffers::Vector<float>> input) {
    fbb_.AddOffset(Observable::VT_INPUT, input);
  }
  void add_another_input(int32_t another_input) {
    fbb_.AddElement<int32_t>(Observable::VT_ANOTHER_INPUT, another_input, 0);
  }
  explicit ObservableBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ObservableBuilder &operator=(const ObservableBuilder &);
  flatbuffers::Offset<Observable> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Observable>(end);
    return o;
  }
};

inline flatbuffers::Offset<Observable> CreateObservable(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<float>> input = 0,
    int32_t another_input = 0) {
  ObservableBuilder builder_(_fbb);
  builder_.add_another_input(another_input);
  builder_.add_input(input);
  return builder_.Finish();
}

inline flatbuffers::Offset<Observable> CreateObservableDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<float> *input = nullptr,
    int32_t another_input = 0) {
  return Observation::CreateObservable(
      _fbb,
      input ? _fbb.CreateVector<float>(*input) : 0,
      another_input);
}

}  // namespace Observation

#endif  // FLATBUFFERS_GENERATED_OBSERVABLE_OBSERVATION_H_
